<a href="https://colab.research.google.com/github/ashik0007/testDataset/blob/master/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [31]:
m = 10000
X = np.random.randint(low = 0, high = 255, size = (12288,m))
y = np.random.randint(low = 0, high = 2, size = (1,m))
print(X)
print(np.shape(X))
print(y)
print(np.shape(y))

[[ 26 164  75 ...  40 177 213]
 [ 18  68  22 ...  23 167  75]
 [251 241 249 ...  50  95  82]
 ...
 [246 217 238 ...   8 160 112]
 [168 128 117 ... 184 113  70]
 [107 140  28 ...  82 139 122]]
(12288, 10000)
[[0 1 0 ... 1 1 1]]
(1, 10000)
